import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/lib/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MovieSearch",
  description: "Generated by create next app",
  icons: {
    icon: "/film.svg", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
           
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Navbar />
          {children}
          {/* <Footer /> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
